version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: api
    restart: always
    build: ./
    ports:
      - "80:3000"
    depends_on:
      - mongo
